# Generated by Django 5.2 on 2026-09-17 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ecomm_category_ecomm_address_ecomm_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomm_order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
        migrations.RemoveField(
            model_name='ecomm_cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ecomm_cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ecomm_product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='ecomm_favourite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ecomm_favourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ecomm_orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ecomm_orderitem',
            name='product',
        ),
        migrations.RenameField(
            model_name='ecomm_order',
            old_name='razorpay_signeture',
            new_name='razorpay_signature',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ecomm_order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ecomm_order',
            name='order_placed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ecomm_order',
            name='payment_mode',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online payment')], default='cod', max_length=20),
        ),
        migrations.DeleteModel(
            name='Ecomm_Address',
        ),
        migrations.DeleteModel(
            name='Ecomm_Cart',
        ),
        migrations.DeleteModel(
            name='Ecomm_Category',
        ),
        migrations.DeleteModel(
            name='Ecomm_Favourite',
        ),
        migrations.DeleteModel(
            name='Ecomm_OrderItem',
        ),
        migrations.DeleteModel(
            name='Ecomm_Product',
        ),
    ]
