# Generated by Django 5.2 on 2026-09-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ecomm_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecomm_orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelTable(
            name='ecomm_orderitem',
            table='core_order_items',
        ),
    ]
